stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            sluggable: true
            timestampable: true
        db_dev:
            sluggable: true
            timestampable: true