atypik_house_reservation:
    resource: "@AtypikHouseBundle/Controller/ReservationController.php"
    type:     annotation

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

atypik_house:
    resource: "@AtypikHouseBundle/Resources/config/routing.yml"
    prefix:   /

payment:
    resource: "@PaymentBundle/Resources/config/routing.yml"
    prefix:   /payment

housing:
    resource: "@HousingBundle/Resources/config/routing.yml"
    prefix:   /

tools:
    resource: "@ToolsBundle/Resources/config/routing.yml"
    prefix:   /tools

# Lexit Auth
#api_login_check:
#    path: /api/login_check

# Sonata Media Routing
gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

# JWT Auth
api_login_check:
    path: /api/login_check

# FOS Routing
fos_user:
    resource: "@UserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

#KMS Froala
kms_froala_editor:
  resource: "@KMSFroalaEditorBundle/Resources/config/routing.yml"
  prefix:   /froalaeditor

#HWI OAUTH
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /login

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

facebook_login:
    path: /login/check-facebook

linkedin_login:
    path: /login/check-linkedin

google_login:
    path: /login/check-google

#Payum Routing
payum_all:
    resource: "@PayumBundle/Resources/config/routing/all.xml"
