# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_PROPRIETARY:
            - ROLE_USER
        ROLE_NEWS_MANAGER:
            - ROLE_USER
        ROLE_ADMIN:
            - ROLE_USER
            - ROLE_PROPRIETARY
            - ROLE_ALLOWED_TO_SWITCH
        ROLE_IT:
            - ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            switch_user: true
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:       true
            anonymous:    true
            oauth:
                resource_owners:
                    facebook: "/login/check-facebook"
                    google: "/login/check-google"
                login_path: /login
                failure_path: /login
                default_target_path: /register
                use_forward: false
                oauth_user_provider:
                    service: atypikhouse.user_provider

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
