atypikhouse_housing_index:
    path:     /list
    defaults: { _controller: "HousingBundle:Housing:all" }

atypikhouse_housing_show:
    path:     /show/{slug}
    defaults: { _controller: "HousingBundle:Housing:show" }

atypikhouse_housing_:
    path:     /
    defaults: { _controller: "HousingBundle:Housing:" }

atypikhouse_housing_list_proprietary_housing:
    path:     /admin/proprietary/housing
    defaults: { _controller: "HousingBundle:Housing:listProprietaryHousing" }

