#Atypikhouse Housing User part
atypikhouse_housing:
    resource: "@HousingBundle/Resources/config/routing/housing.yml"
    prefix:   /housing

atypikhouse_housing_notation:
    resource: "@HousingBundle/Resources/config/routing/housing_notation.yml"
    prefix:   /review

#Atypikhouse Housing Admin part
atypikhouse_admin_housing:
    resource: "@HousingBundle/Resources/config/routing/housing_admin.yml"
    prefix:   /admin/housing

atypikhouse_admin_housing_detail:
    resource: "@HousingBundle/Resources/config/routing/housing_details.yml"
    prefix:   /admin/housing/detail

atypikhouse_admin_housing_type:
    resource: "@HousingBundle/Resources/config/routing/housing_type.yml"
    prefix:   /admin/housing-type

atypikhouse_admin_housing_notation_type:
    resource: "@HousingBundle/Resources/config/routing/housing_notation_type.yml"
    prefix:   /admin/housing-notation-type

atypikhouse_admin_housing_notation:
    resource: "@HousingBundle/Resources/config/routing/housing_notation_admin.yml"
    prefix:   /admin/review

#API Part
atypikhouse_api_housing:
    resource: "@HousingBundle/Resources/config/routing/housing_api.yml"
    prefix:   /api/housing

atypikhouse_api_housing_admin:
    resource: "@HousingBundle/Resources/config/routing/housing_admin_api.yml"
    prefix:   /api/admin/housing