<?php

namespace AtypikHouseBundle\Repository;

use AtypikHouseBundle\Entity\Reservation;
use Doctrine\ORM\EntityRepository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends EntityRepository
{

    /**
     * Get the reservation of the proprietary
     *
     * @param int $id Get the proprietary user id
     *
     * @return Reservation[]
     */
    public function getProprietaryReservation(int $id)
    {
        $qb = $this->createQueryBuilder('r');

        $qb
            ->leftJoin('r.housing', 'h')
            ->leftJoin('h.proprietary', 'pr')
            ->where('pr.id = :userId')
            ->setParameter('userId', $id);

        return $qb->getQuery()->getResult();
    }

    /**
     * Get all reviews for a house
     *
     * @param string $slug Get the housing slug
     *
     * @return Reservation[]
     */
    public function getHousingReviews(string $slug)
    {
        $qb = $this->createQueryBuilder('r');

        $qb
            ->select('r')
            ->innerJoin('r.housing', 'h')
            ->innerJoin('r.review', 'rw')
            ->where('h.slug = :slug')
            ->andWhere('r.deletedAt IS NULL')
            ->setParameter('slug', $slug);

        return $qb->getQuery()->getResult();
    }
}
