atypikhouse_reservation_index:
    path:     /
    defaults: { _controller: "AtypikHouseBundle:Reservation:index" }
    methods:  GET

atypikhouse_reservation_list_proprietary_reservation:
    path:     /admin/proprietary/reservation
    defaults: { _controller: "AtypikHouseBundle:Reservation:listProprietaryReservation" }
    methods:  GET

atypikhouse_reservation_show:
    path:     /{id}/show
    defaults: { _controller: "AtypikHouseBundle:Reservation:show" }
    methods:  GET

atypikhouse_reservation_new:
    path:     /new
    defaults: { _controller: "AtypikHouseBundle:Reservation:new" }
    methods:  [GET, POST]

atypikhouse_reservation_edit:
    path:     /{id}/edit
    defaults: { _controller: "AtypikHouseBundle:Reservation:edit" }
    methods:  [GET, POST]

atypikhouse_reservation_delete:
    path:     /{id}/delete
    defaults: { _controller: "AtypikHouseBundle:Reservation:delete" }
    methods:  DELETE
